theme: jekyll-theme-midnight
title: "Café Gato"
description: "The Café Gato official website, featuring all the information you could possibly need."
gitorg: "https://github.com/drewreed2005/cafegato"
description: "Opening February 2023"
google_analytics:
